#!/bin/bash
#SBATCH --job-name=dt
#SBATCH --partition=s_standard
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --time=03:00:00

module purge
module load tools/octopus/11.4
#module load mpi/openmpi/3.1.2-gcc-7.3.0


export OMP_NUM_THREADS=1
/cluster/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/openmpi-3.1.2-af7zrcesig4lnjlho2aewuwpozudwv2e/bin/orterun -np $SLURM_NTASKS octopus 
